version: "3.9"

services:
  scraper:
    build: .
    container_name: job_scraper
    volumes:
      - ./jobs_database.duckdb:/app/jobs_database.duckdb
      - ./logs:/app/logs
    restart: unless-stopped
    command: ["python", "script.py"]

  dashboard:
    build: .
    container_name: job_dashboard
    ports:
      - "8501:8501"
    depends_on:
      - scraper
    volumes:
      - ./jobs_database.duckdb:/app/jobs_database.duckdb
    restart: unless-stopped
    command: ["streamlit", "run", "dashboard.py", "--server.port=8501", "--server.address=0.0.0.0"]
